### ISSUE TITLE
only works with ember-cli < 2.15.0

### ISSUE THREAD

**Issue by jbailey4** [ember-engines/engine-blueprint#11]
There is an explicit call to `Addon.generatePackageJson` [here](https://github.com/ember-engines/engine-blueprint/blob/master/index.js#L110) in `/index.js`. Seems like this method was renamed to `updatePackgeJson` in ember-cli [here](https://github.com/ember-cli/ember-cli/commit/2a946538c416baa59a3276e4d43b045f2a6684de#diff-456c4ad7f3699d6c18e7c009f37676f2R35), and released in `ember-cli@2.15.0`.

Downgrading to a version of ember-cli <2.15.0 works with this blueprint.

Perhaps this could be mentioned in the README for now until this blueprint is updated.

**Comment by mike183** [comment]
Submitted #12
